apiVersion: v1
kind: Pod
metadata:
  name: ci-sonarqube-data
spec:
  containers:
    - name: postgres
      image: docker.io/postgres:13.7
      resources:
        requests:
          cpu: "0.25"
          memory: "256Mi"
        limits:
          cpu: "0.5"
          memory: "512Mi"
      env:
        - name: POSTGRES_USER
          value: "sonarqube"
        - name: POSTGRES_PASSWORD
          value: "sonar99sonar"
      volumeMounts:
        - name: ci-sonarqube-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: ci-sonarqube-data
      hostPath:
        path: /data/ci-sonarqube-data
        type: DirectoryOrCreate
---
apiVersion: v1
kind: Pod
metadata:
  name: ci-sonarqube
spec:
  containers:
    - name: sonarqube
      image: docker.io/sonarqube:9.9.1-community
      resources:
        requests:
          cpu: "0.5"
          memory: "1024Mi"
        limits:
          cpu: "1"
          memory: "2048Mi"
      env:
        - name: SONAR_JDBC_URL
          value: "jdbc:postgresql://ci-sonarqube-data:5432/sonarqube?charSet=UNICODE"
        - name: SONAR_JDBC_USERNAME
          value: "sonarqube"
        - name: SONAR_JDBC_PASSWORD
          value: "sonar99sonar"
      volumeMounts:
        - name: ci-sonarqube-extensions
          mountPath: /opt/sonarqube/extensions
        - name: ci-sonarqube-esdata
          mountPath: /opt/sonarqube/data
  volumes:
    - name: ci-sonarqube-extensions
      hostPath:
        path: /data/ci-sonarqube-extensions
        type: DirectoryOrCreate
    - name: ci-sonarqube-esdata
      hostPath:
        path: /data/ci-sonarqube-esdata
        type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: ci-sonarqube
spec:
  selector:
    app.kubernetes.io/name: ci-sonarqube
  ports:
    - name: web
      port: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ci-sonarqube
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
  - http:
      paths:
      - path: /sonarqube
        pathType: Prefix
        backend:
          service:
            name: ci-sonarqube
            port:
              number: 9000
